[build]
  base    = "frontend/gestion-front"      # cd aquí antes de build
  publish = "frontend/gestion-front/build" # carpeta final estática
  command = "npm run build"               # tu comando de build

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
