# Generated by Django 5.2 on 2025-05-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('calle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle')),
                ('numero_exterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número interior')),
                ('colonia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio/Delegación')),
                ('entidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad federativa')),
                ('especialidad', models.CharField(max_length=200)),
                ('numero_trabajador', models.CharField(max_length=50, unique=True, verbose_name='Número de trabajador')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=20, verbose_name='Género')),
                ('categoria', models.CharField(choices=[('Definitivo', 'Definitivo'), ('Tiempo Completo', 'Tiempo Completo'), ('Otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('grado_academico', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Otro', 'Otro')], max_length=50, verbose_name='Grado académico')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
            ],
        ),
    ]
