# Generated by Django 5.2 on 2025-05-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'No binario'), ('Otro', 'Otro')], max_length=20, verbose_name='Género'),
        ),
    ]
